### ISSUE TITLE
[Mockup] - User saved datasets

### ISSUE THREAD

**Issue by GD-Dheer** [Data-Boom/SOEN490#427]
As a User, I would like to visually see all my saved datasets on a page.

**Description** 
Users need a page to see all their saved datasets under a profile tab

**Tasks**
- [x] Task: Create Mockup to show what this page should look like

**Acceptance Criteria**
- Mockup Link delivered

**Comment by ds161833** [comment]
After thorough consideration, it was decided that the mockup is not needed since the ui component to be used, already exists. the View Saved Datasets page should display the datasets in this component:
![image](https://user-images.githubusercontent.com/22376976/109421381-15f6e980-79a5-11eb-993b-5f21afd0acec.png)
This component is called SearchResults.tsx in client
